### ISSUE TITLE
Memory Leak in AppIntroFragment

### ISSUE THREAD

**Issue by boguszpawlowski** [AppIntro/AppIntro#790] opened 2020-05-20 21:18 UTC
**AppIntro Version**: 6.0.0

**Device/Android Version**: 
Reproduced on Xiaomi Mi 9T pro (Android 10), Google Pixel 2 (Android 10)

**Issue details / Repro steps / Use case background**:  
After switching tabs back and forth, main layout of AppIntroFragment is leaking.

**Your Code**: 
```
import android.content.Intent
import android.os.Bundle
import androidx.fragment.app.Fragment
import com.github.appintro.AppIntro2
import com.github.appintro.AppIntroFragment

class AppIntroActivity : AppIntro2() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        addSlide(
            AppIntroFragment.newInstance(
                title = "dnsaodnaush",
                description = "iasdjoas"
            )
        )
        addSlide(
            AppIntroFragment.newInstance(
                title = "dasjdoiajsias",
                description = "diojsaoidjsa"
            )
        )
        addSlide(
            AppIntroFragment.newInstance(
                title = "dshadhas",
                description = "ndasnjk"
            )
        )
        addSlide(
            AppIntroFragment.newInstance(
                title = "dnasnduas",
                description = "dashuidhasdsa"
            )
        )
        addSlide(
            AppIntroFragment.newInstance(
                title = "joiadsjoisa",
                description = "dhasodhs"
            )
        )
    }


    override fun onSkipPressed(currentFragment: Fragment?) {
        super.onSkipPressed(currentFragment)

        goToMainActivity()
    }

    override fun onDonePressed(currentFragment: Fragment?) {
        super.onDonePressed(currentFragment)

        goToMainActivity()
    }

    private fun goToMainActivity() {
        startActivity(Intent(this, MainActivity::class.java))
        finish()
    }
}
```

**Leak trace:  (Captured via LeakCanary)**:
```ruby
┬
├─ android.view.inputmethod.InputMethodManager
│    Leaking: NO (InputMethodManager↓ is not leaking and a class is never leaking)
│    GC Root: System class
│    ↓ static InputMethodManager.sInstance
├─ android.view.inputmethod.InputMethodManager
│    Leaking: NO (DecorView↓ is not leaking and InputMethodManager is a singleton)
│    ↓ InputMethodManager.mCurRootView
├─ com.android.internal.policy.DecorView
│    Leaking: NO (LinearLayout↓ is not leaking and View attached)
│    mContext instance of com.android.internal.policy.DecorContext, wrapping activity com.example.AppIntroActivity with mDestroyed = false
│    Parent android.view.ViewRootImpl not a android.view.View
│    View#mParent is set
│    View#mAttachInfo is not null (view attached)
│    View.mWindowAttachCount = 1
│    ↓ DecorView.mContentRoot
├─ android.widget.LinearLayout
│    Leaking: NO (AppIntroActivity↓ is not leaking and View attached)
│    mContext instance of com.example.AppIntroActivity with mDestroyed = false
│    View.parent com.android.internal.policy.DecorView attached as well
│    View#mParent is set
│    View#mAttachInfo is not null (view attached)
│    View.mWindowAttachCount = 1
│    ↓ LinearLayout.mContext
├─ com.example.leak.AppIntroActivity
│    Leaking: NO (ArrayList↓ is not leaking and Activity#mDestroyed is false)
│    ↓ AppIntroActivity.fragments
├─ java.util.ArrayList
│    Leaking: NO (Object[]↓ is not leaking)
│    ↓ ArrayList.elementData
├─ java.lang.Object[]
│    Leaking: NO (AppIntroFragment↓ is not leaking)
│    ↓ array Object[].[2]
├─ com.github.appintro.AppIntroFragment
│    Leaking: NO (Fragment#mFragmentManager is not null)
│    Fragment.mTag=android:switcher:2131231213:2
│    ↓ AppIntroFragment.mainLayout
│                       ~~~~~~~~~~
╰→ androidx.constraintlayout.widget.ConstraintLayout
​     Leaking: YES (ObjectWatcher was watching this)
​     mContext instance of com.example.AppIntroActivity with mDestroyed = false
​     View#mParent is null
​     View#mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     key = 748015d1-78a1-4136-b5af-08291475354a
​     watchDurationMillis = 5660
​     retainedDurationMillis = 659
​     key = ce82fde8-88ec-4fef-88f1-ddf48db679de
​     watchDurationMillis = 5661

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.0
Analysis duration: 6039 ms 
```

**Comment by cortinico** [comment] 2020-05-20 21:35
Thanks for the report. Probably a duplicate of #419 
We anyway need to spend some time to investage this. Any support is more than welcome.

**Comment by boguszpawlowski** [comment] 2020-05-20 21:45
Added pr regarding this. After clearing main layout in AppIntroBaseFragment the issue is gone. I checked it on the sample app with LeakCanary

**Comment by cortinico** [comment] 2020-05-20 22:35
Thanks again for the contribution to AppIntro 🙏

**Closed** 2020-05-20 22:34 UTC
Labels: bug, help wanted
