### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71

### ISSUE THREAD

**Issue by nicolabeghin** [AppIntro/AppIntro#716] opened 2019-10-21 19:51 UTC
**AppIntro Version**: 5.1.0

**Device/Android Version**: Android emulator, API 28

**Issue details**: 
When switching to AndroidX and updating lib version to 5.1.0, the following error is thrown while compiling

`Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.`

**Tried to solve**:
```
implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.2.71'
```

and 

`ext.kotlin_version = '1.2.71'`

in `build.gradle` (top level, buildscript) where `maven { url 'https://jitpack.io' }` is available already

**Comment by paolorotolo** [comment] 2019-10-24 14:39
Latest version of AppIntro is almost 1 year old, therefore this should be already fixed in ```master```. Can you please if this is solved using latest alpha?
```
implementation 'com.github.AppIntro:appintro:6.0.0-alpha3'
```

Anyway, I plan to release a new stable version this we.

**Comment by nicolabeghin** [comment] 2019-10-24 18:28
Just tried, unfortunately didn't solve the issue.

**Comment by paolorotolo** [comment] 2019-10-24 21:03
Can you provide an example project where this happens so I can give it a try?

**Comment by cortinico** [comment] 2019-10-24 21:04
Hi @nicolabeghin 
Can you please share the whole `build.gradle` file. I have the feeling you're missing some repositories configuration.

**Comment by nicolabeghin** [comment] 2019-10-24 22:03
top-level `build.gradle`

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    buildscript {
        repositories {
            jcenter()
            google()
            maven {
                url 'https://maven.fabric.io/public'
            }
            maven { url 'https://jitpack.io' }
            flatDir {
                dirs '../aars'
            }
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.5.1'
            classpath 'com.google.gms:google-services:4.3.2'
            classpath 'io.fabric.tools:gradle:1.28.0'
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
            maven { url 'https://jitpack.io' }
            maven { url "https://maven.google.com" }
            flatDir {
                dirs '../aars'
            }
        }
    }

module `build.gradle`

    plugins {
        id 'com.android.application'
        id 'com.github.triplet.play' version '2.1.0'
        id 'io.fabric'
    }
    
    Properties properties = new Properties()
    properties.load(file("../environment.properties").newDataInputStream())
    
    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        compileSdkVersion 29
        defaultConfig {
            applicationId = "com.org"
            vectorDrawables.useSupportLibrary = true
            multiDexEnabled true
            minSdkVersion 14
            targetSdkVersion 29
            versionCode 111
            versionName "1.2.3"
            buildConfigField "boolean", "storecheck", "true"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled true
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
                signingConfig signingConfigs.release
            }
        }
    }
    
    dependencies {
        implementation 'com.github.AppIntro:appintro:6.0.0-alpha3'
    }
    
    apply plugin: 'com.google.gms.google-services'

**Comment by cortinico** [comment] 2019-10-24 22:08
Can I ask you to provide a full stacktrace? Looks like your Gradle Sync is also failing right? If this is the case, would you be able to run:
`./gradlew tasks --info --stacktrace` and post the result?

**Comment by nicolabeghin** [comment] 2019-10-25 20:24
thanks @cortinico for your attention.

1. no error with the aforementioned command
2. got error with `./gradlew build` that pointed me to a conflict with `okhttp:4.2.2` (!!!) - any specific reason for this?

```
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50.
     Required by:
         project :myappLib > org.jetbrains.kotlin:kotlin-stdlib:1.3.50
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints: 
           Dependency path 'MyApp:myappLib:unspecified' --> 'com.squareup.okhttp3:okhttp:4.2.2' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.50' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50'
           Constraint path 'MyApp:myappLib:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.31}' because of the following reason: fullwpDebugRuntimeClasspath uses version 1.3.31

```

Anyway, just for the sake of testing, I removed dependency (`androidTestImplementation` dependency, which is even stranger)
`androidTestImplementation 'com.squareup.okhttp3:okhttp:4.2.2'`

and got one step ahead with these 2 errors, which seems related to AndroidX/Google libraries. I tried updating to any last version library but didn't get past this, will look into this in the upcoming days.

```
<home>/.gradle/caches/transforms-2/files-2.1/0105642395ce85983c36ab05f9128dc5/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
<home>.gradle/caches/transforms-2/files-2.1/0105642395ce85983c36ab05f9128dc5/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
```
If you have any suggestion in regards to latest `okhttp` incompatibility with `AppIntro` kindly let me know!

**Comment by paolorotolo** [comment] 2019-10-26 18:11
So I tried to set up an example project with okHttp and AppIntro and all runs smoothly. Are you able to provide us a minimal project where this happens?

**Comment by nicolabeghin** [comment] 2019-10-27 11:46
@paolorotolo I think it happens in connection to other Google libraries, here's the whole dependencies block. If still not able to reproduce, I'll provide a sample project but as of right now I was able to use the stable version so no need to worry :D

    dependencies {
        implementation project(path: ':aFileChooser', configuration: 'default')
        implementation 'androidx.appcompat:appcompat:1.1.0'
        implementation 'androidx.legacy:legacy-support-v4:1.0.0'
        implementation 'com.google.android.material:material:1.0.0'
        implementation 'de.mindpipe.android:android-logging-log4j:1.0.3'
        implementation 'com.google.android.gms:play-services-base:17.1.0'
        implementation 'com.github.AppIntro:appintro:6.0.0-alpha3'
        implementation 'androidx.multidex:multidex:2.0.1'
        implementation 'net.lingala.zip4j:zip4j:2.2.3'
        implementation 'log4j:log4j:1.2.17'
        implementation project(path: ':lvl_library', configuration: 'default')
        implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
        implementation 'com.google.firebase:firebase-analytics:17.2.0'
        implementation 'com.nononsenseapps:filepicker:4.2.1'
    
        // Google Drive REST API v2
        implementation 'com.google.android.gms:play-services-auth:16.0.1'
        implementation('com.google.api-client:google-api-client-android:1.29.2'){
            exclude(group: 'xpp3', module: 'xpp3')
            exclude(group: 'org.apache.httpcomponents', module: 'httpclient')
            exclude(group: 'junit', module: 'junit')
            exclude(group: 'com.google.android', module: 'android')
        }
        implementation ('com.google.apis:google-api-services-drive:v2-rev362-1.25.0'){
            exclude(group: 'xpp3', module: 'xpp3')
            exclude(group: 'org.apache.httpcomponents', module: 'httpclient')
            exclude(group: 'junit', module: 'junit')
            exclude(group: 'com.google.android', module: 'android')
        }
    
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
        androidTestImplementation 'androidx.test:runner:1.1.0'
        androidTestImplementation 'androidx.test:rules:1.1.0'
        androidTestImplementation 'androidx.test.ext:junit:1.1.0'
        androidTestImplementation 'com.squareup.okhttp3:okhttp:4.2.2'
        androidTestImplementation(name:'cloudtestingscreenshotter_lib', ext:'aar')
    }

**Comment by cortinico** [comment] 2019-10-28 12:25
> If still not able to reproduce, I'll provide a sample project

Hi @nicolabeghin, Yeah that would be beneficial as I'm still unable to isolate or reproduce your issue.

**Comment by cortinico** [comment] 2020-05-11 20:16
@nicolabeghin Please let us know if you still have the problem. I'm closing the issue for inactivity.

**Closed by cortinico** 2020-05-11 20:16 UTC
