### ISSUE TITLE
I'm getting following error

### ISSUE THREAD

**Issue by gaadeveloper** [AppIntro/AppIntro#669] opened 2019-04-26 08:55 UTC
I'm getting the following error at the google console, which makes it harder to debug for me... I know it has to do with this library. The version of the library that I'm using is 'com.github.AppIntro:AppIntro:6.0.0-alpha1'. Any help is appreciated.

```
java.lang.OutOfMemoryError: 
  at dalvik.system.VMRuntime.newNonMovableArray (Native Method)
  at android.graphics.BitmapFactory.nativeDecodeAsset (Native Method)
  at android.graphics.BitmapFactory.decodeStream (BitmapFactory.java:620)
  at android.graphics.BitmapFactory.decodeResourceStream (BitmapFactory.java:455)
  at android.graphics.drawable.Drawable.createFromResourceStream (Drawable.java:1152)
  at android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:724)
  at android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:575)
  at android.content.res.Resources.getDrawable (Resources.java:767)
  at android.content.Context.getDrawable (Context.java:525)
  at androidx.core.content.ContextCompat.getDrawable (ContextCompat.java:454)
  at androidx.appcompat.widget.ResourceManagerInternal.getDrawable (ResourceManagerInternal.java:144)
  at androidx.appcompat.widget.ResourceManagerInternal.getDrawable (ResourceManagerInternal.java:132)
  at androidx.appcompat.content.res.AppCompatResources.getDrawable (AppCompatResources.java:104)
  at androidx.appcompat.widget.AppCompatImageHelper.setImageResource (AppCompatImageHelper.java:86)
  at androidx.appcompat.widget.AppCompatImageView.setImageResource (AppCompatImageView.java:93)
  at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView (AppIntroBaseFragment.kt:116)
  at androidx.fragment.app.Fragment.performCreateView (Fragment.java:2539)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:875)
  at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManagerImpl.java:1227)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:1293)
  at androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:710)
  at androidx.fragment.app.FragmentManagerImpl.executeOps (FragmentManagerImpl.java:2063)
  at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether (FragmentManagerImpl.java:1853)
  at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManagerImpl.java:1808)
  at androidx.fragment.app.FragmentManagerImpl.execSingleAction (FragmentManagerImpl.java:1685)
  at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:560)
  at androidx.fragment.app.FragmentPagerAdapter.finishUpdate (FragmentPagerAdapter.java:148)
  at androidx.viewpager.widget.ViewPager.populate (ViewPager.java:1244)
  at androidx.viewpager.widget.ViewPager.populate (ViewPager.java:1092)
  at androidx.viewpager.widget.ViewPager$3.run (ViewPager.java:273)
  at androidx.viewpager.widget.ViewPager.completeScroll (ViewPager.java:2005)
  at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent (ViewPager.java:2135)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2212)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2672)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2301)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2672)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2301)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2672)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2301)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2672)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2301)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2672)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2301)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2672)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2301)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:411)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1810)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3076)
  at com.github.paolorotolo.appintro.AppIntroBase.dispatchTouchEvent (AppIntroBase.java:306)
  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:69)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:373)
  at android.view.View.dispatchPointerEvent (View.java:10162)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4446)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4314)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3861)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3914)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3880)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4007)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3888)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4064)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3861)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3914)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3880)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3888)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3861)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6257)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6196)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6157)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6360)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:192)
  at android.os.MessageQueue.nativePollOnce (Native Method)
  at android.os.MessageQueue.next (MessageQueue.java:323)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:6154)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)
```

**Comment by cortinico** [comment] 2019-05-03 15:20
Closing as this is a duplicate of #551 
You're probably using an image that is too big

**Closed by cortinico** 2019-05-03 15:20 UTC
