### ISSUE TITLE
Samsung display camera cutout background issue

### ISSUE THREAD

**Issue by andreynovikov** [AppIntro/AppIntro#931] opened 2021-03-05 09:27 UTC
AppIntro 6.1.0, running in landscape mode on Samsung device does not set background color of camera cutout:

![Screenshot_20210305-120620_Trekarta](https://user-images.githubusercontent.com/2943625/110094022-65c22000-7dac-11eb-9c68-93c8853174e9.jpg)

This vertical grey strip on the left is the place where camera hole is on real display.

When I enable `showStatusBar(true)` it looks like this:

![Screenshot_20210305-120641_Trekarta](https://user-images.githubusercontent.com/2943625/110094247-a9b52500-7dac-11eb-94b3-402a38818400.jpg)

In portrait mode without `showStatusBar(true)` it looks the same as in landscape mode. But with `showStatusBar(true)` it looks perfectly correct (no grey cutouts):

![Screenshot_20210305-120652_Trekarta](https://user-images.githubusercontent.com/2943625/110094438-e1bc6800-7dac-11eb-92af-f2487f0c7c5e.jpg)

**Comment by andreynovikov** [comment] 2021-03-05 09:55
Have tried to set `LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES` in AppIntro activity but it didn't help.

**Comment by cortinico** [comment] 2021-03-05 18:58
So if I understand correctly the issue is with cutouts only on portrait mode right?
Can I ask you to try on an official emulator (like a Pixel) and post screenshots of the Intro with the Cutout enabled in Developer's tools?

**Comment by cortinico** [comment] 2021-10-31 18:07
Closing as the author is unresponsive and there is nothing actionable

**Closed by cortinico** 2021-10-31 18:07 UTC
Labels: bug, help wanted
