### ISSUE TITLE
goToNextSlide(), goToPreviousSlide() and showSkipButton(boolean) not publicly accessible anymore in 6.x.x

### ISSUE THREAD

**Issue by nicolabeghin** [AppIntro/AppIntro#717] opened 2019-10-25 20:30 UTC
Hi everyone
I'm updating to latest 6.x.x beta version (as suggested in #716). Seems like some sort of regression was introduced, since the aforementioned methods `goToNextSlide()` and `goToPreviousSlide()` and `showSkipButton(boolean)` (as shown in #475, #498 and #531) are not publicly accessible anymore. Would it be possible to make them publicly available again? 

ref. https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.kt#L167

thanks
nicola

**Comment by paolorotolo** [comment] 2019-10-26 09:40
I can't remember any reason why those methods should not be public.
@cortinico this actually happened during our kotlin rewrite, if you're ok there are also more methods I would expose in the API in that class.

**Comment by paolorotolo** [comment] 2019-10-29 18:49
@cortinico since you rewrote those classes in Kotlin, can you give me green light to refactor this please? Could be the only blocking issue for next stable release.

**Comment by cortinico** [comment] 2019-11-04 01:37
Hey @paolorotolo Sorry for the late reply.

Thanks for the heads up @nicolabeghin. Please note that 6.x is going to be a major release with a lot of breaking changes. Ideally we're going to publish a short guide with an overview of the API change to provide support to the user.

So here a quick recap on the status of those methods:

- `showSkipButton` -> Method has been removed. You can now use the `isButtonsEnabled` property in Kotlin (or the `setSkipButtonEnabled` in Java). The behavior is the same as the former method.

- `goToNextSlide` -> Method is protected. This is intentional as previously everything was generally public. Ideally the default visibility should be `protected` instead as you can call those methods from your `AppIntro` subclass. If you need to extend the visibility you can still do it overriding those methods.

- `goToPreviusSlide` -> Method is private. This is actually wrong as it should be private. @paolorotolo can you fix this or I can also do it.

Thanks again for reporting @nicolabeghin :)

**Comment by nicolabeghin** [comment] 2019-11-11 15:28
thanks @cortinico ! IMHO `goToNextSlide` / `goToPreviusSlide`  should remain `public` in order to enable programmatic slide change. If you have another suggestion (other than extending the class, which I would consider a regression in some way), kindly let me know.

**Comment by cortinico** [comment] 2019-11-20 18:07
> goToNextSlide / goToPreviusSlide should remain public in order to enable programmatic slide change.

They're currently protected so you can still achieve programmatic slide change, but only inside the `AppIntro` subclasses. If you need to expose those methods further (e.g. you have other components interacting with your AppIntro), you need to intentionally extend the visibility.

**Comment by cortinico** [comment] 2020-05-11 20:15
Closing as we released 6.0.0 last week and the issue is solved.

**Closed by cortinico** 2020-05-11 20:15 UTC
Labels: support
