### ISSUE TITLE
addSlide IndexOutOfBoundsException on Android 7

### ISSUE THREAD

**Issue by Eichhof** [AppIntro/AppIntro#836] opened 2020-07-07 20:42 UTC
AppIntro Version: 5.1.0

Device/Android Version: Huawei P9 Plus / Android 7.0

Issue details / Repro steps / Use case background: The tutorial slides load sucessfully and the first video is played but when I want to go to the next video it crashes with the exception shown below. This only happens on Android 7. On a Samsung S10 with Android 10 it works fine.

Your Code:

```
public class TutorialActivity extends AppIntro {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Note here that we DO NOT use setContentView();

        boolean full = getIntent().getBooleanExtra("full", true);

        // Add your slide fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.
        if (full) {
            addSlide(TutorialFragment.newInstance("1. Keyboard", R.raw.keyboard));
            addSlide(TutorialFragment.newInstance("2. Self-Reports", R.raw.self_report));
            addSlide(TutorialFragment.newInstance("2.1. Example 1", R.raw.example1));
            addSlide(TutorialFragment.newInstance("2.2. Example 2", R.raw.example2));
            addSlide(TutorialFragment.newInstance("2.3. Example 3", R.raw.example3));
            addSlide(TutorialFragment.newInstance("2.4. Example 4", R.raw.example4));
            addSlide(TutorialFragment.newInstance("3. App", R.raw.app));
        } else {
            addSlide(TutorialFragment.newInstance("Definition", R.raw.self_report));
            addSlide(TutorialFragment.newInstance("Example 1", R.raw.example1));
            addSlide(TutorialFragment.newInstance("Example 2", R.raw.example2));
            addSlide(TutorialFragment.newInstance("Example 3", R.raw.example3));
            addSlide(TutorialFragment.newInstance("Example 4", R.raw.example4));
        }

        // Set Background color
        setBarColor(Color.parseColor("#0069B4"));
        setSeparatorColor(Color.parseColor("#0069B4"));

        // Show Skip button
        showSkipButton(true);

        // Show how far progress is
        setProgressButtonEnabled(true);

        // Don't Turn vibration on
        setVibrate(false);

        // Set animation for changing fragment
        setZoomAnimation();
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);

        finishTutorial();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);

        finishTutorial();
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);

        if(newFragment instanceof TutorialFragment) {
            ((TutorialFragment) newFragment).startVideo();
        }
        if(oldFragment instanceof TutorialFragment) {
            ((TutorialFragment) oldFragment).stopVideo();
        }
    }

    /**
     * Closes the Tutorial activity
     *
     */
    private void finishTutorial() {
        finish();
    }
}

public class TutorialFragment extends Fragment {

    private static final String EXTRA_TITLE = "extra_title";
    public static final String EXTRA_VIDEO = "extra_video";

    private VideoView mVideoView;

    public static final TutorialFragment newInstance(String title, int videoId) {
        // Load tutorial data
        TutorialFragment f = new TutorialFragment();
        Bundle bd = new Bundle(2);
        bd.putString(EXTRA_TITLE, title);
        bd.putInt(EXTRA_VIDEO, videoId);
        f.setArguments(bd);
        return f;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        ViewGroup rootView = (ViewGroup) inflater.inflate(R.layout.fragment_tutorial, container, false);

        // Set tutorial title
        TextView title = rootView.findViewById(R.id.tutorial_title);
        title.setText(getArguments().getString(EXTRA_TITLE));

        // Set tutorial video
        mVideoView = rootView.findViewById(R.id.tutorial_video);

        // Load video file
        String path = "android.resource://" + getContext().getPackageName() + "/" + getArguments().getInt(EXTRA_VIDEO);
        Uri uri= Uri.parse(path);

        // Set video parameters
        mVideoView.setMediaController(null);
        mVideoView.setVideoURI(uri);
        mVideoView.requestFocus();

        return rootView;
    }

    /**
     * Start running the video
     *
     */
    public void startVideo() {
        mVideoView.start();
        mVideoView.seekTo(0);
    }

    /**
     * Stops running the video
     *
     */
    public void stopVideo() {
        mVideoView.stopPlayback();
    }
}
```

Stack trace / LogCat:

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2

--------- Stack trace ---------

    java.util.ArrayList.get(ArrayList.java:411)
    androidx.viewpager.widget.ViewPager.getChildDrawingOrder(ViewPager.java:804)
    android.view.View.populateAccessibilityNodeInfoDrawingOrderInParent(View.java:7010)
    android.view.View.onInitializeAccessibilityNodeInfoInternal(View.java:6969)
    android.view.View.onInitializeAccessibilityNodeInfo(View.java:6584)
    android.view.View.createAccessibilityNodeInfoInternal(View.java:6543)
    android.view.View.createAccessibilityNodeInfo(View.java:6528)
    android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
    android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
    android.view.View.onInitializeAccessibilityEventInternal(View.java:6480)
    android.view.View.onInitializeAccessibilityEvent(View.java:6468)
    android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6329)
    android.view.View.sendAccessibilityEventUnchecked(View.java:6314)
    android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:23705)
    android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:23738)
    android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:9476)
    android.view.View.onFocusChanged(View.java:6197)
    android.view.View.clearFocusInternal(View.java:6101)
    android.view.View.unFocus(View.java:6134)
    android.view.ViewGroup.unFocus(ViewGroup.java:997)
    android.view.ViewGroup.unFocus(ViewGroup.java:997)
    android.view.ViewGroup.unFocus(ViewGroup.java:997)
    android.view.ViewGroup.requestChildFocus(ViewGroup.java:734)
    android.view.ViewGroup.addViewInner(ViewGroup.java:4503)
    android.view.ViewGroup.addView(ViewGroup.java:4312)
    androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
    android.view.ViewGroup.addView(ViewGroup.java:4252)
    android.view.ViewGroup.addView(ViewGroup.java:4225)
    androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:326)
    androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
    androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
    androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
    androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
    androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
    androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
    androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
    androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
    androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
    androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
    androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:246)
    androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
    androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
    androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
    androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:612)
    com.github.paolorotolo.appintro.AppIntroViewPager.setCurrentItem(AppIntroViewPager.java:84)
    com.github.paolorotolo.appintro.AppIntroViewPager.goToNextSlide(AppIntroViewPager.java:47)
    com.github.paolorotolo.appintro.AppIntroBase.changeSlide(AppIntroBase.java:965)
    com.github.paolorotolo.appintro.AppIntroBase.access$300(AppIntroBase.java:41)
    com.github.paolorotolo.appintro.AppIntroBase$NextButtonOnClickListener.onClick(AppIntroBase.java:1059)
    android.view.View.performClick(View.java:5646)
    android.view.View$PerformClick.run(View.java:22459)
    android.os.Handler.handleCallback(Handler.java:761)
    android.os.Handler.dispatchMessage(Handler.java:98)
    android.os.Looper.loop(Looper.java:156)
    android.app.ActivityThread.main(ActivityThread.java:6523)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by cortinico** [comment] 2020-07-08 12:15
Thanks for reporting.
It seems like a bug, but I'm not able to reproduce it a first run.

Are you able to provide a sample project (or edit the AppIntro sample app in a separate branch) to replicate this crash?

**Comment by Eichhof** [comment] 2020-07-09 11:48
I will try to make a sample project.

What is weird is that it only happens for the TutorialActivity shown above. I also have a Setup in my app (shown at the first launch of the app) and in this setup I also add a lot of slides (addSlide) but not using TutorialFragment.class. And it works...

When I only add up to two Slides in the TutorialActivity it also works but with more than two Slides it crashes.

Is there something wrong with the code shown above?

**Comment by cortinico** [comment] 2020-07-09 16:32
> Is there something wrong with the code shown above?

Seems like the code is correct

**Comment by Eichhof** [comment] 2020-07-10 22:07
Ok but why is then for the piece of code I have shown not working on Android 7 but at another place (setup of app) it is working when I add more than 2 slides.

**Comment by frdnwr** [comment] 2021-02-12 22:08
Hi, I have the same issue, my crashlytics report shows the error on android 5,6, and 8 ... 

Anything i can provide to help with solving it? 

> Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
>        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
>        at java.util.ArrayList.get(ArrayList.java:308)
>        at com.github.appintro.internal.viewpager.PagerAdapter.getItem(PagerAdapter.kt:13)
>        at com.github.appintro.AppIntroBase$onPostCreate$1.run(AppIntroBase.kt:458)

**Comment by cortinico** [comment] 2021-02-12 22:12
> Anything i can provide to help with solving it?

On which version of AppIntro are you?

**Comment by frdnwr** [comment] 2021-02-12 22:15
> 
> On which version of AppIntro are you?

latest, 6.0.0

**Comment by frdnwr** [comment] 2021-02-12 22:25
I've just noticed i wasn't using the latest version....

**Comment by cortinico** [comment] 2021-02-13 13:45
@frdnwr Can you update to the latest version and try again? If you could provide a reproducer that would be awesome

**Comment by frdnwr** [comment] 2021-04-02 13:41
I'm still getting the same crash .. it doesn't happen to all users I don't know what causes it .. but it still shows up on crash reports 

> This issue has 377 crash events affecting 129 users

> Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
>  at com.github.appintro.AppIntroBase$onPostCreate$1.run(AppIntroBase.kt:458)

I'm using the latest version .. 
Is there a solution for this ?

**Comment by cortinico** [comment] 2021-04-03 12:28
>  Is there a solution for this ?

Not at this time. If we don't have a reproducer is hard to understand what could be causing this.

**Comment by kebiro** [comment] 2021-05-12 14:40
Hey,

we've also had this issue. Overall very similar to OP in that we also have a custom fragment, etc., although that seems to be irrelevant in our case.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sensing.core.coreviewer, PID: 16883
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.github.appintro.internal.viewpager.PagerAdapter.getItem(PagerAdapter.kt:13)
        at com.github.appintro.AppIntroBase$onPostCreate$1.run(AppIntroBase.kt:458)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6749)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
```

I can reproduce this by not adding any slides in `onCreateView`.

**Comment by kebiro** [comment] 2021-05-12 14:57
Hey,

we've also had this issue.

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.github.appintro.internal.viewpager.PagerAdapter.getItem(PagerAdapter.kt:13)
        at com.github.appintro.AppIntroBase$onPostCreate$1.run(AppIntroBase.kt:458)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6749)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

I can reproduce this by not adding any slides in onCreateView.

(I had to delete the previous post due to privacy reasons.)

**Comment by rndstr** [comment] 2021-05-16 02:04
Looks like on my device `AppIntroBase#onPostCreate()` is called before my activity's `onCreate()` which inherits from `AppIntro`, I set breakpoints to confirm this.

I'm using the exact sample code from the README and on `v6.1.0`.

Device is a Teclast tablet running Android 10.

Also the comment in https://github.com/AppIntro/AppIntro/blob/85350b289644c3d4bb2dfbf884044e83d5ad6103/appintro/src/main/java/com/github/appintro/AppIntroBase.kt#L459 is not true, it doesn't return null but throws `IndexOutOfBoundsException`.

**Comment by rndstr** [comment] 2021-05-16 17:13
I found the issue, my Activity overrode the wrong `onCreate()`:

```
    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
```
instead of
```
    override fun onCreate(savedInstanceState: Bundle?) {

```
which fixes the `com.github.appintro.AppIntroBase$onPostCreate` triggered `java.lang.IndexOutOfBoundsException` exception.

I think everything after https://github.com/AppIntro/AppIntro/issues/836#issuecomment-778481616 is not about the OP's issue but doing the same mistake I did.

**Comment by cortinico** [comment] 2021-05-19 13:07
There is not much we can do here tbh.
@frdnwr @kebiro Do you confirm that you experienced the same scenario reported by @rndstr? Are you still facing this issue?

The OP issue is related to a older version of the library and I'm not really able to reproduce it.

**Comment by cortinico** [comment] 2021-05-20 07:59
I'm closing this as incomplete. Should someone have a similar problem, please open a new issue and we'll try to fix it 👍

**Closed by cortinico** 2021-05-20 07:59 UTC
Labels: bug, incomplete

**Comment by czlucius** [comment] 2022-02-03 14:25
I seem to also experience the same issue. On Android 12, it happens no matter how many slides I add, on my device, Samsung Galaxy S20 FE 5G.
Thank you!

**Comment by cortinico** [comment] 2022-02-03 15:48
> Should someone have a similar problem, please open a new issue and we'll try to fix it 👍

Please open a separate issue and provide a reproducer 🙏
