### ISSUE TITLE
Back Button Is Overlapping ?

### ISSUE THREAD

**Issue by heihitesh** [AppIntro/AppIntro#1001] opened 2022-01-29 11:22 UTC
I am using AppIntro in Java Android 12 

The back button is overlapping previous next button, As shown in the image 

![ss2](https://user-images.githubusercontent.com/13065741/151659039-ee804ffb-3780-4d8a-8f2c-70e9526e9a26.jpg)
![ss1](https://user-images.githubusercontent.com/13065741/151659041-776d9fe0-a69a-41f5-9c55-c8768a76ea82.jpg)

Please check this out 

Thank You

**Comment by cortinico** [comment] 2022-01-29 15:16
That's interesting 🤔 Are you using an emulator?

**Comment by heihitesh** [comment] 2022-01-29 16:13
No, 
This issue is seen in Android 7 & 12 
I am using Java for the App

**Comment by cortinico** [comment] 2022-02-01 21:30
I'm not able to reproduce this.
Can I ask you to provide a reproducer? Ideally something that would work on a emulator, so that I could look into it?

**Comment by heihitesh** [comment] 2022-02-03 09:50
Hi, this issue is seen in a real device. SAMSUNG API version 31

I haven't pushed the changes yet ..
Once done I can send you the app url

Thank you

**Comment by 245938767** [comment] 2022-05-31 03:47
I also encountered this problem
```
Both properties are set
 isWizardMode = true 
 isSkipButtonEnabled = true
```
 The back button and the skip button will be displayed overlaid
Drive Version
```
    android 12
    sdk 32
    implementation 'com.github.AppIntro:AppIntro:6.2.0'


```
```class AppIntroActivity : AppIntro2() {
    private val thisTitleColor = R.color.black
    private val thisdpColor = R.color.black
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        addSlide(
            AppIntroFragment.createInstance(
                title = "titleOne",
                description = "description",
                titleColorRes = thisTitleColor,
                imageDrawable = R.drawable.p7,
                backgroundColorRes = R.color.white,
                descriptionColorRes = thisdpColor,
            )
        )
        addSlide(
            AppIntroFragment.createInstance(
                title = "titleTow",
                description = "description",
                titleColorRes = thisTitleColor,
                imageDrawable = R.drawable.p8,
                backgroundColorRes = R.color.teal_200,
                descriptionColorRes = thisdpColor,
            )
        )
        setTransformer(AppIntroPageTransformerType.Fade)
        // 开启震动
        isVibrate = true
        vibrateDuration = 50L
        //开启返回按钮
        isWizardMode = true
        //开启渐变
        isColorTransitionsEnabled = true
        //开启跳过按钮
        isSkipButtonEnabled = true
        //设置沉浸模式
        setImmersiveMode()
    }

    override fun onSkipPressed(currentFragment: Fragment?) {
        super.onSkipPressed(currentFragment)
        // Decide what to do when the user clicks on "Skip"
        startActivity(Intent(this@AppIntroActivity, MainActivity::class.java))
        finish()
    }

    override fun onDonePressed(currentFragment: Fragment?) {
        super.onDonePressed(currentFragment)
        // Decide what to do when the user clicks on "Done"
        startActivity(Intent(this@AppIntroActivity, MainActivity::class.java))
        finish()
    }
}```

**Comment by cortinico** [comment] 2022-05-31 16:25
> The back button and the skip button will be displayed overlaid

Same as above. Is this something can be reproduced on emulator consistently?

**Comment by cortinico** [comment] 2024-02-02 15:51
Closed by https://github.com/AppIntro/AppIntro/pull/1179

**Closed by cortinico** 2024-02-02 15:51 UTC
Labels: incomplete
