### ISSUE TITLE
remove slide

### ISSUE THREAD

**Issue by TheProgrammingM** [AppIntro/AppIntro#709] opened 2019-08-30 10:31 UTC
Hey, i wanted to ask how to remove a slide, because in my AppIntro the user can login and after it i want to show some other screens like: "Please ckeck your crendentials" or "Your login was successfull". If the login wasn't successfull, the slide automatically goes back, but it is still there if you swipe from right to left. Here is a part of my code:

> 

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addSlide(SampleSlide.newInstance(R.layout.slide_1));
        addSlide(SampleSlide.newInstance(R.layout.slide_2));
        addSlide(SampleSlide.newInstance(R.layout.slide_3));
        setVibrate(true);
        setVibrateIntensity(40);
        setColorDoneText(getResources().getColor(R.color.colorIntromenu));
        setColorSkipButton(getResources().getColor(R.color.colorIntromenu));
        setNextArrowColor(getResources().getColor(R.color.colorIntromenu));
        setIndicatorColor(R.color.colorAccent, R.color.colorIntromenu);
        showSkipButton(false);
        setDoneText("Login");
    }

And this is a part of my login in "onDonePressed":

> 

    runOnUiThread(new Runnable(){
       public void run() {
            addSlide(SampleSlide.newInstance(R.layout.slide_4_servererror));
            pager.goToNextSlide();
             final Handler handler = new Handler();
             handler.postDelayed(new Runnable() {
             @Override
                  public void run() {
                        // Do something after 4s = 4000ms
                        pager.setCurrentItem(2);
                        }
                    }, 4000);
               }
        });

**Comment by cortinico** [comment] 2019-09-03 15:29
Hi @TheProgrammingM 
As for now, there is no easy way to dynamically remove a slide.

The workaround that I'd suggest is to use a slide with a custom fragment and handle all the custom logic there.

**Comment by cortinico** [comment] 2020-05-11 20:17
Closing here. @TheProgrammingM feel free to reopen if the issue is not solved.

**Closed by cortinico** 2020-05-11 20:17 UTC
Labels: support
