### ISSUE TITLE
Sample App Rewrite Help[Design]

### ISSUE THREAD

**Issue by AnuthaDev** [AppIntro/AppIntro#656] opened 2019-03-14 04:38 UTC
**AppIntro Version**: Upcoming

**Issue details / Repro steps / Use case background**: I actually have 2 ideas on developing the sample App:
1. Stays mostly the same with the addition of a new slide for parallax and colour transform.--> Relatively simple to grasp.

2. The app starts and we have a Scroll view with a bunch of cardviews inside, the cardviews contain customizability options for the activity layout, fragment layout, button styles, indicator etc. i.e. Users can see the full potential of this library before including it. We have a FAB that starts the intro activity with the values set in the first activity. So, We have only 2 activities, one for AppIntro and one for AppIntro2, other things such as permissions and animations are configured in the first activity and the values passed on to the Intro activity, which configured itself based on the values provided to it (using Intent) -->A little bit harder to understand, but offers the full potential of the library.

I am with 2 as I believe, we can write the Readme well enough that users won't need to look inside the app (the second approach isn't that complicated anyway). 

Just let me know what you want, so I can proceed

**Comment by cortinico** [comment] 2019-03-15 01:02
Would it be possible to have like an hybrid solution?

Like I would definitely skip the ViewPager with the examples we have now and I'll just have a list of Buttons that fires an AppIntro with some hardcoded settings.

We can still have a _customizer_ as you mentioned. I think it's really cool, although I don't expect major usage. Usually developers tends to run a sample app for not more than say 1 minute.

**Comment by Anutha02** [comment] 2019-03-15 02:22
@cortinico, I am thinking the same, I will improve on the design and talk about it soon

**Comment by cortinico** [comment] 2019-03-15 17:45
Great looking forward :)

**Comment by Anutha02** [comment] 2019-03-24 15:21
@cortinico Alright so, here is my concept: when the app opens, we present 5 cardviews: AppIntro 1,2,3 , permissionslide, customize. The first 4 cardviews open their respective default activities. The fifth cardview opens a new activity with options to customize the intro. We can enhance the app by adding the GitHub source code link under each cardview. So I will create some mock ups and post here when I get time. Tell me your thoughts.

**Comment by cortinico** [comment] 2019-03-26 23:56
Looks good to me :)

> We can enhance the app by adding the GitHub source code link under each cardview

Probably not really worth the pain. Developers are not going to copy-n-paste code from the App. The will anyway use the code from the Github page/Readme.

**Comment by cortinico** [comment] 2020-05-11 20:23
Closing as duplicate of #563
I'm also linking the issue in the other issue so discussion doesn't get lost

**Closed by cortinico** 2020-05-11 20:23 UTC
Labels: support
