### ISSUE TITLE
required=false in askForPermissions is ignored on API >= 30

### ISSUE THREAD

**Issue by vernazza** [AppIntro/AppIntro#1141] opened 2023-09-16 13:28 UTC
## 🐛 Describe the bug
Recently I release an update with latest AppIntro with POST_NOTIFICATIONS permission but if the user refuses it, the slides do not progress.
The `required` parameter should let the user to continue, and this is what happens with other permissions. with POST_NOTIFICATIONS this doesn't happen.

## ✅ Expected behavior
If the user refuses the notification permission he should continue to the next slide

## 💣 Steps to reproduce
Run the sample code

## 📑 Your Code
```
     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (!NotificationManagerCompat.from(this).areNotificationsEnabled()) {             
                addSlide([...])

                askForPermissions(
                    permissions = arrayOf(android.Manifest.permission.POST_NOTIFICATIONS),
                    slideNumber = 3,
                    required = false
                )
            }
        }
```

## 📱 Tech info
 - AppIntro Version: 6.3.1
 - Device: Pixel 7
 - Android OS Version: 13.0

**Comment by paolorotolo** [comment] 2023-09-19 21:49
Hi @vernazza! Thanks for reaching out.
I've tried to reproduce the issue and I didn't succeed at first. Then I found out that `required = false` seems to be ignored for all the times subsequent to the first when asking for `POST_NOTIFICATIONS`.
I'm currently investigating what causes this behavior.

Meanwhile, can you confirm this test case?
1. Uninstall your app and install it again
2. Navigate to intro permission request
3. Deny `POST_NOTIFICATIONS` with required=false`
4. * The intro navigates to the following slide *
5. Open the intro again
6. Try again to deny the permission
7. * The intro gets stuck on the permission slide *

**Comment by paolorotolo** [comment] 2023-09-19 22:02
Little update, it seems the issue is also present when asking for other permissions like `CAMERA`. I think it's not related to the specific permission but to SDK version used.
`CAMERA` works fine on API 28 but has the same issue written on the comment above on API 31. 

I'm looking for API behavior changes we might need to take into account.

**Comment by paolorotolo** [comment] 2023-09-19 22:20
Done a little debugging, the issue is related to a platform change introduced in Android 11: "[Permission Dialog Visibility](https://developer.android.com/about/versions/11/privacy/permissions#dialog-visibility)".



> Starting in Android 11, if the user taps Deny for a specific permission more than once during your app's lifetime of installation on a device, the user doesn't see the system permissions dialog if your app requests that permission again. The user's action implies "don't ask again." On previous versions, users would see the system permissions dialog each time your app requested a permission, unless the user had previously selected a "don't ask again" checkbox or option.

When the permission is marked as "don't ask again" by the OS, the AppIntro's code to filter "not required permissions" doesn't get run. A PR with a fix is on the way.

**Comment by cortinico** [comment] 2023-09-20 08:22
Closed by https://github.com/AppIntro/AppIntro/pull/1143

**Closed by cortinico** 2023-09-20 08:22 UTC
Labels: bug
